### ISSUE TITLE
 env = stack()[1][0].f_globals?

### ISSUE THREAD

**Issue by alpha0067** [joegagliardo/bettersql#1]
i  think  it  is  a more powerful library than pandasql, however, it only include f_globals?
i failed when i run in locals()?
perhaps it is more perfect if  you can  add the similar  local variables .

**Comment by joegagliardo** [comment]
I just did a quick fix to also search locals. See if it works better for you. Thanks a bunch for reporting this to me.

**Comment by joegagliardo** [comment]
Thanks. Good advice. I’ll look into it. But you should also be able to pass in any dataframe manually instead of relying on the automatic detection from globals or locals.
